# Generated by Django 5.0.1 on 2026-01-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
