# Generated by Django 5.0.1 on 2026-01-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemrequest_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flavor_type',
            field=models.CharField(choices=[('bitter', 'Bitter'), ('caramel', 'Caramel'), ('chocolatey', 'Chocolatey'), ('coffee-like', 'Coffee-like'), ('creamy', 'Creamy'), ('crisp', 'Crisp'), ('dry', 'Dry'), ('earthy', 'Earthy'), ('floral', 'Floral'), ('fruity', 'Fruity'), ('full-bodied', 'Full-bodied'), ('funky', 'Funky'), ('herbal', 'Herbal'), ('honeyed', 'Honeyed'), ('hoppy', 'Hoppy'), ('light-bodied', 'Light-bodied'), ('malty', 'Malty'), ('nutty', 'Nutty'), ('refreshing', 'Refreshing'), ('roasty', 'Roasty'), ('session', 'Session'), ('smoky', 'Smoky'), ('smooth', 'Smooth'), ('sour', 'Sour'), ('spicy', 'Spicy'), ('strong', 'Strong'), ('sweet', 'Sweet'), ('tart', 'Tart'), ('toasted', 'Toasted'), ('woody', 'Woody'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='flavor_type',
            field=models.CharField(choices=[('bitter', 'Bitter'), ('caramel', 'Caramel'), ('chocolatey', 'Chocolatey'), ('coffee-like', 'Coffee-like'), ('creamy', 'Creamy'), ('crisp', 'Crisp'), ('dry', 'Dry'), ('earthy', 'Earthy'), ('floral', 'Floral'), ('fruity', 'Fruity'), ('full-bodied', 'Full-bodied'), ('funky', 'Funky'), ('herbal', 'Herbal'), ('honeyed', 'Honeyed'), ('hoppy', 'Hoppy'), ('light-bodied', 'Light-bodied'), ('malty', 'Malty'), ('nutty', 'Nutty'), ('refreshing', 'Refreshing'), ('roasty', 'Roasty'), ('session', 'Session'), ('smoky', 'Smoky'), ('smooth', 'Smooth'), ('sour', 'Sour'), ('spicy', 'Spicy'), ('strong', 'Strong'), ('sweet', 'Sweet'), ('tart', 'Tart'), ('toasted', 'Toasted'), ('woody', 'Woody'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
