# Generated by Django 5.0.1 on 2026-01-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_flavor_type_to_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
