# Generated by Django 5.0.1 on 2026-01-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_percentage_poi_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
