# Generated by Django 5.0.1 on 2026-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
