# Generated by Django 5.0.1 on 2026-01-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_percentage_to_item_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
