# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_brand_to_item_and_item_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='volumen',
            field=models.CharField(blank=True, help_text='Free text e.g. 33cl, 1 L, 500ml', max_length=50),
        ),
    ]
