# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_volumen_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='volumen',
            field=models.CharField(blank=True, help_text='Free text e.g. 33cl, 1 L, 500ml', max_length=50),
        ),
    ]
